name: publish
run-name: Publish
on:
  push:
    branches:
      - "main"
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-node@v4
        name: Setup node
        with:
          node-version: 20
      - run: npm ci
        name: NPM install
      - run: npm run build-storybook
        name: Build Storybook
      - uses: JamesIves/github-pages-deploy-action@v4
        name: Deploy Storybook
        with:
          folder: storybook-static
      - uses: JS-DevTools/npm-publish@v3
        name: Deploy NPM
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - uses: martinbeentjes/npm-get-version-action@v1
        id: get-package-version
        name: Get package.json version
      - uses: elgohr/Github-Release-Action@v5
        name: Create a release
        with:
          title: ${{ steps.get-package-version.outputs.current-version }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
